title: "Uday Santhosh Raju Vysyaraju"
description: "Portfolio showcasing my expertise in computer vision and machine learning."
theme: minimal-mistakes-jekyll
url: "https://your-github-username.github.io"
baseurl: "/personal-portfolio"

author:
  name: "Uday Santhosh Raju Vysyaraju"
  email: "uday@tamu.edu"
  linkedin: "https://www.linkedin.com/in/uday-santhosh-raju-v/"
  github: "https://github.com/vusr"

# Navigation links
nav:
  - title: "Home"
    url: "/"
  - title: "Skills"
    url: "/skills/"
  - title: "Projects"
    url: "/projects/"
  - title: "Workshops"
    url: "/workshops/"
  - title: "Contact"
    url: "/contact/"
